composition-api-setup page translated
vuejs-translations/docs-bn pull request #18
Opened 2023-08-11 10:06 UTC by abuansarpatowary

## Description of Problem

## Proposed Solution

## Additional Information

2023-08-11 10:08 UTC, abuansarpatowary commented
@mahmudunnabikajal all done from the new branch. Check this out now

2023-08-11 15:11 UTC, abuansarpatowary commented
@mahmudunnabikajal everything is okay on your side to accept my translation?

2023-08-11 16:11 UTC, mahmudunnabikajal requested changes
@abuansarpatowary  Check this correction

2023-08-11 17:01 UTC, abuansarpatowary commented
@mahmudunnabikajal changed the issues that you mentioned

2023-08-11 19:08 UTC, mahmudunnabikajal commented on src/api/composition-api-setup.md
>  If you are using Composition API with Single-File Components, [`<script setup>`](/api/sfc-script-setup) is strongly recommended for a more succinct and ergonomic syntax.
translate this to bangla

2023-08-11 19:13 UTC, mahmudunnabikajal commented on src/api/composition-api-setup.md
> +## প্রপস অ্যাক্সেস করা {#accessing-props}
```## প্রপস অ্যাক্সেস করা {#accessing-props}```  don't translate title to banlga. because it will not work on the server.

2023-08-11 19:15 UTC, mahmudunnabikajal commented on src/api/composition-api-setup.md
> +আপনার যদি সত্যিই প্রপগুলিকে ডিস্ট্রাকচার করতে হয়, বা রিয়েক্টিভিটি বজায় রাখার সময় একটি বহিরাগত ফাংশনে একটি প্রপ pass করতে হয়, আপনি [toRefs()](./reactivity-utilities#torefs) এবং [toRef()](এর সাথে এ
Error: ```[toRef()](এর সাথে এটি করতে পারেন /api/reactivity-utilities#toref)``` 

recheck this 64 no line.

2023-08-11 19:17 UTC, mahmudunnabikajal requested changes
@abuansarpatowary check similar errors.

2023-08-13 06:38 UTC, abuansarpatowary commented
@mahmudunnabikajal check this now. Fixes all error that you mentioned

2023-08-13 13:18 UTC, merged

2023-08-13 13:32 UTC, mahmudunnabikajal commented
@abuansarpatowary translation already merge with branch ```api/composition-api-setup.md``` and i see you don't translate from line ```82 to 171``` . Make sure you are translating updated code from main branch. Check and create a pull request on branch ```api/composition-api-setup.md``` again.

2023-08-13 16:22 UTC, abuansarpatowary commented
@mahmudunnabikajal entire page has been translated now.